### ISSUE TITLE
老兄，理论上，我是不是只要照着你的说明文档中的dockerfile文件直接打包镜像，配置一下gpt的api的id信息，就能跑了？

### ISSUE THREAD

**Issue by miaomangdelang** [stevenyu113228/OpenAI-GPT-3-Telegram-Chatbot#1]

**Comment by miaomangdelang** [comment]
https://blog.stevenyu.tw/2022/12/04/%E5%88%A9%E7%94%A8-openai-gpt-3-%E5%AF%AB%E4%B8%80%E5%80%8B-telegram-%E8%81%8A%E5%A4%A9%E6%A9%9F%E5%99%A8%E4%BA%BA-cloudflare-tunnel-gcp-appengine/

**Comment by stevenyu113228** [comment]
我這邊沒有提供 Docker 映像，不過理論上需要 Docker 的話，只需要在 python image 裝 flask, openai 跟 Telegram 就可以用了。
除此之外只需要修改 config 檔案的那些 access token
